stages:
  - build
  - deploy_gcp

build_images:
  stage: build
  image: docker:20.10.16

  services:
    - docker:20.10.16-dind
  
  variables: 
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS

  script:
    - docker build -t gabrieloliver001/mysql:1.0 mysql/.
    - docker push gabrieloliver001/mysql:1.0
    - docker build -t gabrieloliver001/kube-projeto-final-app:1.0 app/.
    - docker push gabrieloliver001/kube-projeto-final-app:1.0

deploy_gcp:

  stage: deploy_gcp

  before_script:
    - chmod 400 $SSH_KEY
  
  script:
      - ssh -o StrictHostKeyChecking=no -i $SSH_KEY gcp@$SSH_SERVER "sudo rm -Rf ./kube-projeto-final-app/ && git clone https://gitlab.com/gabrieloliver001/kube-projeto-final-app.git && cd kube-projeto-final-app && sudo chmod +x ./script.sh && ./script.sh"

